variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "availability_domain" {}
variable "compartment_ocid" {}
variable "subnet_ocid" {}
variable "image_ocid" {}
variable "ssh_public_key_path" {}